from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker, declarative_base
import os

# //postgres(superusuario de postgresql):
# proyectocrm(contrasena de postgresql)@localhost:5432/prueba(nombre de la base de datos)"
# SQLALCHEMY_DATABASE_URL = "postgresql://postgres:proyecto@localhost:5432/prueba"
SQLALCHEMY_DATABASE_URL = "postgresql://postgres:proyecto@localhost:5432/prueba"

engine = create_engine(SQLALCHEMY_DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def create_table():
    Base.metadata.create_all(bind=engine)

    if engine.dialect.name == "postgresql":
        with engine.begin() as conn:
            result = conn.execute(
                text(
                    "SELECT is_identity, column_default FROM information_schema.columns "
                    "WHERE table_schema = 'public' "
                    "AND table_name = 'reporte' "
                    "AND column_name = 'id_reporte'"
                )
            ).fetchone()
            if result is not None:
                is_identity, column_default = result
                if is_identity == "NO" and column_default is None:
                    try:
                        conn.execute(
                            text(
                                "ALTER TABLE reporte "
                                "ALTER COLUMN id_reporte ADD GENERATED BY DEFAULT AS IDENTITY"
                            )
                        )
                    except Exception:
                        pass

            seq_name = conn.execute(
                text("SELECT pg_get_serial_sequence('reporte','id_reporte')")
            ).scalar()
            if seq_name:
                max_id = conn.execute(
                    text("SELECT COALESCE(MAX(id_reporte), 0) FROM reporte")
                ).scalar()
                if max_id is not None:
                    try:
                        conn.execute(
                            text("SELECT setval(:seq, :value, true)"),
                            {"seq": seq_name, "value": max_id},
                        )
                    except Exception:
                        pass
