from .usuario import Usuario
from .cliente import Cliente
from .campania import Campania
from .cliente_campania import ClienteCampania
from .oportunidad import Oportunidad
from .cotizacion import Cotizacion
from .venta import Venta
from .pedido import Pedido
from .factura import Factura
from .atencion_cliente import AtencionCliente
from .notificacion import Notificacion
from .reporte import Reporte
from .reporte_analisis import ReporteAnalisis
