from . import clientes_web
from . import campanias_web
from . import oportunidades_web
from . import cotizaciones_web
from . import ventas_web
from . import pedidos_web
from . import facturas_web
from . import atencion_cliente_web
from . import usuarios_web
from . import notificaciones_web
from . import reportes_web
from . import auth_web